- name: Install Jenkins
  docker_container:
    name: jenkins
    image: jenkins/jenkins
    state: started
    pull: true
    recreate: yes
    restart_policy: always
    published_ports:
      - 8080:8080
